### ISSUE TITLE
Incluir Nota Promissória

### ISSUE THREAD

**Issue by beatrizazanha** [rmobis/estatuto-intercomp#9]

**Comment by beatrizazanha** [comment]
Verificar se Nota Promissória deixa o nome sujo

**Comment by danilo-valente** [comment]
Pelo que eu li não deixa o nome automaticamente sujo, mas abre a possibilidade de abrir uma ação judicial contra alguém que não pagar:

- https://www.jurisway.org.br/v2/pergunta.asp?idmodelo=20329
- https://blog.quantosobra.com.br/nota-promissoria-o-que-e/

**Comment by danilo-valente** [comment]
Como não depende de alteração no Estatuto, vou simplesmente fechar essa issue.
